---
title: "Simulation"
output: html_document
---

# Libraries
```{r}
suppressPackageStartupMessages({
  library(Biostrings)
  library(AnnotationHub)
  library(rtracklayer)
})
# ah <- AnnotationHub(localHub = TRUE)
# ensdb <- query(ah, c("GRCm38", "EnsDb"))[[1]]
# genome <- getGenomeTwoBitFile(ensdb)
```

# miRNAs
```{r}
fa <- readRNAStringSet("https://www.mirbase.org/ftp/CURRENT/mature.fa.gz")
fa <- DNAStringSet(fa)
names(fa) <- gsub(" .+", "", names(fa))
fa <- fa[grep(pattern = "mmu", x = names(fa))]

# cluster chr17:17830188-17830879
clusterMirs <- c(
  "mmu-miR-125a-5p", "mmu-miR-99b-5p", "mmu-let-7e-5p",
  "mmu-let-7e-3p", "mmu-miR-99b-3p", "mmu-miR-125a-3p"
)
clusterMirs <- fa[clusterMirs]

sizefacts <- c(
  SRR13129037 = 0.98, SRR13129041 = 0.78, SRR13129038 = 1.63,
  SRR13129043 = 0.88, SRR13129039 = 0.93, SRR13129040 = 1.46,
  SRR13129042 = 0.66, SRR13129036 = 1.47
)

set.seed(123)
clusterMirsCounts <- t(sapply(rgamma(length(clusterMirs), shape = 3), function(x) {
  sizefacts * exp(1 + x) * rnorm(8, mean = rep(c(1, rnorm(1, 2, sd = 0.1)), each = 4), sd = 0.4)
}))

row.names(clusterMirsCounts) <- names(clusterMirs)
clusterMirsCounts <- matrix(rnbinom(length(clusterMirsCounts), mu = clusterMirsCounts, size = 2),
  nrow = nrow(clusterMirsCounts), dimnames = dimnames(clusterMirsCounts)
)
clusterMirsCounts
row.names(clusterMirsCounts) <- as.character(clusterMirs)
```

# miRNA precursor
```{r}
# mir144prec <- import(genome, which=GRanges("11", IRanges(78073005,78073070)))
# names(mir144prec) <- "mir144precursor"
mir144prec <- DNAStringSet(c(mir144precursor = substr("GGCTGGGATATCATCATATACTGTAAGTTTGTGATGAGACACTACAGTATAGATGATGTACTAGTC", 1, 50)))
mir144 <- c(mir144prec, fa["mmu-miR-144-3p"], fa["mmu-miR-144-5p"], DNAStringSet(c(
  mir144_invalid1 = "AAGTTTGTGATGAGACACTAC",
  mir144_invalid2 = "CTGTAAGTTTGTGATGAGAC",
  mir144_invalid3 = "ATGTACTAGTCTGGGTA"
)))

set.seed(123)
mu <- rbind(
  abs(rnorm(8, 1)),
  abs(rnorm(8, rep(2:1, each = 4), 0.3)),
  abs(rnorm(8, rep(2:1, each = 4), 0.3)),
  abs(rnorm(8, 1)), abs(rnorm(8, 1)), abs(rnorm(8, 1))
)
mu <- 300 * t(t(mu) * sizefacts)
mir144Counts <- matrix(rnbinom(length(mu), mu = mu, size = 2),
  nrow = nrow(mu),
  dimnames = list(names(mir144), names(sizefacts))
)
row.names(mir144Counts) <- as.character(mir144)


# GGCTGGGATATCATCATATACTGTAAGTTTGTGATGAGACACTACAGTATAGATGATGTACTAGTC       <- precursor
#      GGATATCATCATATACTGTAAGT              TACAGTATAGATGATGTACT           <- mature miRNAs
#                         AAGTTTGTGATGAGACACTAC                            <- size okay, but not valid miRNA
#                     CTGTAAGTTTGTGATGAGAC                                 <- size okay, but not valid miRNA
#                                                        ATGTACTAGTCTGGGTA <- too short, outside


# tRNA-iMet-CAT (with CCA)
# trnaEg <- DNAStringSet(c("tRNA-iMet-CAT" = "GATTGAAACCATCCTCTGCTTCCA"))
# trnaCounts <- ceiling(t(sizefacts * c(1, 2, 4, 1, 140, 180, 120, 110)))
# row.names(trnaCounts) <- "GATTGAAACCATCCTCTGCTTCCA"
```

```{r}
# e <- rbind(clusterMirsCounts, mir144Counts, trnaCounts)
e <- rbind(clusterMirsCounts, mir144Counts)
e
saveRDS(e, file = "readsToSpike.rds")
```
