##############################
## @Author : Deepak Tanwar  ##
## @Date :   20211018       ##
##############################

## Makefile to compile RMarkdown file to HTML.

all: task1
task1:
	Rscript -e 'rmarkdown::render("plots.Rmd", "html_document")' 2> STDERR > STDOUT
